language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

before_script:
  - composer install --prefer-source --no-interaction

script:
  - phpunit -c phpunit.xml
  
notifications:
    email: false
